apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend
  annotations:
    kubernetes.io/change-cause: "{{ .Values.deployment.changecause }}"
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: "nginx:{{ .Values.deployment.imageversion }}"

