deployment:
  replicas: "1"
  changecause: "installing latest version"
  imageVersion: "latest"
service:
  type: LoadBalancer
deployment:
  changeCause: "Initial deployment"
  replicas: 2
  imageVersion: "1.27"

